# Generated by Django 5.0.6 on 2024-07-03 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyiha_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bacground',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='img/')),
            ],
        ),
        migrations.CreateModel(
            name='Watch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('img', models.ImageField(upload_to='25')),
                ('title', models.CharField(max_length=256)),
            ],
        ),
    ]
